name: Deploy PrestaShop Module - Production

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy module to production
        run: |
          sshpass -p "${{ secrets.PROD_SSH_PASSWORD }}" \
          rsync -rvz \
          --no-perms \
          --no-owner \
          --no-group \
          --no-times \
          --omit-dir-times \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='tests' \
          --exclude='vendor' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ \
          ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:${{ secrets.PROD_MODULE_PATH }} || true


      - name: Clear PrestaShop cache (production)
        run: |
          sshpass -p "${{ secrets.PROD_SSH_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} \
          "rm -rf /var/www/prestashop/var/cache/*"
